dto_type = "module"
name = "module"

[fields]
dto_type = "dict"

[fields.Dog]
dto_type = "type"
name = "Dog"

[fields.Dog.fields]
dto_type = "dict"
__doc__ = "null"
__module__ = "module"

[fields.Dog.fields.__init__]
dto_type = "func"
name = "__init__"
closure = "null"

[fields.Dog.fields.make_voice]
dto_type = "func"
name = "make_voice"
closure = "null"

[fields.Dog.fields.__init__.globals]
dto_type = "dict"

[fields.Dog.fields.__init__.code]
dto_type = "dict"
co_argcount = 2
co_code = "7c017c005f0064005300"
co_filename = "/home/matuamod/Documents/Repositories/ISP-2022-053504/second_lab/module.py"
co_firstlineno = 3
co_flags = 67
co_kwonlyargcount = 0
co_lnotab = "0001"
co_name = "__init__"
co_nlocals = 2
co_posonlyargcount = 0
co_stacksize = 2

[fields.Dog.fields.make_voice.globals]
dto_type = "dict"

[fields.Dog.fields.make_voice.code]
dto_type = "dict"
co_argcount = 1
co_code = "740064018301010064005300"
co_filename = "/home/matuamod/Documents/Repositories/ISP-2022-053504/second_lab/module.py"
co_firstlineno = 6
co_flags = 67
co_kwonlyargcount = 0
co_lnotab = "0001"
co_name = "make_voice"
co_nlocals = 1
co_posonlyargcount = 0
co_stacksize = 2

[fields.Dog.fields.__init__.code.co_cellvars]
dto_type = "list"

[fields.Dog.fields.__init__.code.co_consts]
dto_type = "list"
item_0 = "null"

[fields.Dog.fields.__init__.code.co_freevars]
dto_type = "list"

[fields.Dog.fields.__init__.code.co_names]
dto_type = "list"
item_0 = "name"

[fields.Dog.fields.__init__.code.co_varnames]
dto_type = "list"
item_0 = "self"
item_1 = "name"

[fields.Dog.fields.make_voice.code.co_cellvars]
dto_type = "list"

[fields.Dog.fields.make_voice.code.co_consts]
dto_type = "list"
item_0 = "null"
item_1 = "gau-gau-gau"

[fields.Dog.fields.make_voice.code.co_freevars]
dto_type = "list"

[fields.Dog.fields.make_voice.code.co_names]
dto_type = "list"
item_0 = "print"

[fields.Dog.fields.make_voice.code.co_varnames]
dto_type = "list"
item_0 = "self"
